title: Sinitcyn Lab
description: Computational Biomolecular Mass Spectrometry and AI research group
image: /assets/images/logo/lab_logo.blue_wbkg.ver1.png
url: https://sinitcynlab.github.io
baseurl: ""
permalink: /news/:title/
collections:
  posts:
    output: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
theme: null
future: false
include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo/lab_logo.blue_wbkg.ver1.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

